### ISSUE TITLE
Can we read the notification content?

### ISSUE THREAD

**Issue by djprawns** [KingDarBoja/Notification-Listener#1]
As per now, we only see the packagename and notification time stamp. However can we also read the text of the notification?

**Comment by KingDarBoja** [comment]
> As per now, we only see the packagename and notification time stamp. However can we also read the text of the notification?

Sorry for the late response, been busy with Angular stuff.
The text of the notification can be done but I should had to edit the main library source (`notifications`) to provide such data.

I will see what I can do 😉

**Comment by KingDarBoja** [comment]
**UPDATE:** I made a PR to the base library and gonna update this project to provide such functionality, just waiting to get it merged first. Check the PR [here](https://github.com/cph-cachet/flutter-plugins/pull/34).

**Comment by KingDarBoja** [comment]
Closing now as fixed.
